version: '3.9'
services:
  timetracker:
    image: densocreate/timetracker:latest
    container_name: timetracker-app
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    environment:
      DB_HOST=db
      DB_PORT=${DB_PORT}
      DB_USER=${DB_USER}
      DB_PASSWORD=${DB_PASSWORD}
      DB_NAME=${DB_NAME}
      REDIS_HOST=redis
      REDIS_PORT=6379
      APP_PASSWORD=${TIMETRACKER_PASSWORD}  # <your password>
    restart: unless-stopped
  db:
    image: postgres:16-alpine
    container_name: timetracker-postgres
    environment:
      POSTGRES_USER=${DB_USER}
      POSTGRES_PASSWORD=${DB_PASSWORD}
      POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    container_name: timetracker-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
